name: elearn
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  flutter_rating_bar: ^4.0.1

  #    UI
  curved_navigation_bar: ^1.0.3
  http: ^1.1.0
  fluttertoast: ^8.2.2
  dio: ^5.3.4
  modal_progress_hud_nsn: ^0.5.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  glass_kit: ^4.0.1
  glassmorphism_ui: ^0.3.0
  rflutter_alert: ^2.0.7
  flutter_svg: ^2.0.9
  onesignal_flutter: ^5.1.4
  percent_indicator: ^4.2.3
  syncfusion_flutter_pdfviewer: ^26.1.40
  #  Permission & Storage
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  flutter_share: any
  sqflite: ^2.3.0

  #  FireBase
  firebase_core: ^3.1.1
  firebase_dynamic_links: ^6.0.2
  firebase_auth: ^5.1.1

  flutter_facebook_auth: ^7.0.1
  google_sign_in: ^6.1.6
  google_mobile_ads: ^5.0.0
  flutter_fgbg: ^0.3.0
  flutter_html: any
  url_launcher: ^6.2.1
  flutter_phoenix: ^1.1.1
  image_picker: ^1.0.4
  vocsy_epub_viewer: ^2.0.0
  exif: ^3.3.0
  flutter_screenutil: ^5.9.0
  sign_in_with_apple: ^6.0.0
  device_info_plus: ^9.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5


dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/fonts/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          style: italic
    - family: Gilroy-Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          style: italic
    - family: Gilroy-Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
          style: italic
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          style: italic
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true