// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDplhakTd6zncXDkJnL7zYyjCMAltPHkew',
    appId: '1:798167088224:android:87b0ddbd4a80ac5a195705',
    messagingSenderId: '798167088224',
    projectId: 'vocsy-codec-ebook',
    storageBucket: 'vocsy-codec-ebook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOB-SWW9jR5Bg2Vh8KqBUUpx6ZrSzHqNY',
    appId: '1:798167088224:ios:197d0555e208326e195705',
    messagingSenderId: '798167088224',
    projectId: 'vocsy-codec-ebook',
    storageBucket: 'vocsy-codec-ebook.appspot.com',
    androidClientId: '798167088224-1tm0limicqse9tg2693fbqlb8n319idt.apps.googleusercontent.com',
    iosClientId: '798167088224-eksbvbp02oelhajm341uanbpstut8f90.apps.googleusercontent.com',
    iosBundleId: 'com.vinodflutter.ebookonline.OneSignalNotificationServiceExtension',
  );

}